version: '2.0'
services:
  alerta-web:
    image: www.owlemon.com/alerta-web:2017.02.08
    container_name: alerta-web
    ports:
      - 8081:80
    depends_on:
      - alerta-db
    environment:
      - MONGO_URI=mongodb://alerta-db:27017/monitoring
    volumes:
      - $PWD/alerta_config/alertad.conf.example:/etc/alertad.conf
      - $PWD/alerta_config/config.js.example:/app/config.js
    restart: always
  alerta-db:
    image: www.owlemon.com/mongo:2017.02.08
    container_name: mongo
    volumes:
      - /data/mongo:/data/db
    restart: always
  riemann:
    image: mnuessler/riemann
    container_name: riemann
    environment: []
    volumes:
      - "$PWD/riemann_config:/etc/riemann/"
      - "$PWD/plugin_riemann_rabbitmq/etc_default_riemann:/etc/default/riemann"
      - "$PWD/plugin_riemann_rabbitmq/riemann-rabbitmq-input.jar:/usr/lib/riemann/riemann-rabbitmq-input.jar"
    ports: ['5555:5555','5556:5556']
  mq:
    image: rabbitmq:alpine
    container_name: mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE='cookie'
      - RABBITMQ_ENABLE_MANAGEMENT_PLUGIN=true
    hostname: mq
    ports:
      - 5672:5672
